version: "3"
services:
  app_py:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    ports: ["8080:8080"]
    volumes: [./app:/app]
    environment:
      FLASK_ENV: development
      LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
      RESET_SECRET: $RESET_SECRET
  db8:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf